import { Game } from "../interfaces/game.interface";


export const GAMES: Game[] = [
    {
      "id": 1,
      "steam_app_id": 10,
      "name": "Counter-Strike",
      "detailed_description": "Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.",
      "about_the_game": "Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.",
      "short_description": "Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects",
      "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513",
      "capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/10/capsule_231x87.jpg?t=1666823513",
      "capsule_imagev5": "https://cdn.akamai.steamstatic.com/steam/apps/10/capsule_184x69.jpg?t=1666823513",
      "website": null,
      "pc_requirements_minimum": null,
      "pc_requirements_recomended": null,
      "mac_requirements": "Minimum: OS X  Snow Leopard 10.6.3, 1GB RAM, 4GB Hard Drive Space,NVIDIA GeForce 8 or higher, ATI X1600 or higher, or Intel HD 3000 or higher Mouse, Keyboard, Internet Connection",
      "linux_requirements": "Minimum: Linux Ubuntu 12.04, Dual-core from Intel or AMD at 2.8 GHz, 1GB Memory, nVidia GeForce 8600/9600GT, ATI/AMD Radeaon HD2600/3600 (Graphic Drivers: nVidia 310, AMD 12.11), OpenGL 2.1, 4GB Hard Drive Space, OpenAL Compatible Sound Card",
      "developers": "Valve",
      "publishers": "Valve",
      "price": 819,
      "release_date": null,
      "support_info_url": "http://steamcommunity.com/app/10",
      "suport_info_email": null
    },
    {
      "id": 4,
      "steam_app_id": 20,
      "name": "Team Fortress Classic",
      "detailed_description": "One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons, items, and abilities, as teams compete online in a variety of game play modes.",
      "about_the_game": "One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons, items, and abilities, as teams compete online in a variety of game play modes.",
      "short_description": "One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons,",
      "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/20/header.jpg?t=1579634708",
      "capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/20/capsule_231x87.jpg?t=1579634708",
      "capsule_imagev5": "https://cdn.akamai.steamstatic.com/steam/apps/20/capsule_184x69.jpg?t=1579634708",
      "website": null,
      "pc_requirements_minimum": null,
      "pc_requirements_recomended": null,
      "mac_requirements": "Minimum: OS X  Snow Leopard 10.6.3, 1GB RAM, 4GB Hard Drive Space,NVIDIA GeForce 8 or higher, ATI X1600 or higher, or Intel HD 3000 or higher Mouse, Keyboard, Internet Connection",
      "linux_requirements": "Minimum: Linux Ubuntu 12.04, Dual-core from Intel or AMD at 2.8 GHz, 1GB Memory, nVidia GeForce 8600/9600GT, ATI/AMD Radeaon HD2600/3600 (Graphic Drivers: nVidia 310, AMD 12.11), OpenGL 2.1, 4GB Hard Drive Space, OpenAL Compatible Sound Card",
      "developers": "Valve",
      "publishers": "Valve",
      "price": 399,
      "release_date": null,
      "support_info_url": "",
      "suport_info_email": null
    },
    {
      "id": 5,
      "steam_app_id": 30,
      "name": "Day of Defeat",
      "detailed_description": "Enlist in an intense brand of Axis vs. Allied teamplay set in the WWII European Theatre of Operations. Players assume the role of light/assault/heavy infantry, sniper or machine-gunner class, each with a unique arsenal of historical weaponry at their disposal. Missions are based on key historical operations. And, as war rages, players must work together with their squad to accomplish a variety of mission-specific objectives.",
      "about_the_game": "Enlist in an intense brand of Axis vs. Allied teamplay set in the WWII European Theatre of Operations. Players assume the role of light/assault/heavy infantry, sniper or machine-gunner class, each with a unique arsenal of historical weaponry at their disposal. Missions are based on key historical operations. And, as war rages, players must work together with their squad to accomplish a variety of mission-specific objectives.",
      "short_description": "Enlist in an intense brand of Axis vs. Allied teamplay set in the WWII European Theatre of Operations. Players assume the role of light/assault/heavy infantry, sniper or machine-gunner class, each with a unique arsenal of historical weaponry at their disp",
      "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/30/header.jpg?t=1512413490",
      "capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/30/capsule_231x87.jpg?t=1512413490",
      "capsule_imagev5": "https://cdn.akamai.steamstatic.com/steam/apps/30/capsule_184x69.jpg?t=1512413490",
      "website": "http://www.dayofdefeat.com/",
      "pc_requirements_minimum": null,
      "pc_requirements_recomended": null,
      "mac_requirements": "Minimum: OS X  Snow Leopard 10.6.3, 1GB RAM, 4GB Hard Drive Space,NVIDIA GeForce 8 or higher, ATI X1600 or higher, or Intel HD 3000 or higher Mouse, Keyboard, Internet Connection",
      "linux_requirements": "Minimum: Linux Ubuntu 12.04, Dual-core from Intel or AMD at 2.8 GHz, 1GB Memory, nVidia GeForce 8600/9600GT, ATI/AMD Radeaon HD2600/3600 (Graphic Drivers: nVidia 310, AMD 12.11), OpenGL 2.1, 4GB Hard Drive Space, OpenAL Compatible Sound Card",
      "developers": "Valve",
      "publishers": "Valve",
      "price": 399,
      "release_date": null,
      "support_info_url": "",
      "suport_info_email": null
    }
  ]